### PR TITLE
Repository Cleanup & Optimisation

### PR DESCRIPTION
**Pull request by KraigWalker**
- Removed all .DS_Store files
- Added .DS_Store to gitignore
- Removed unnecessary whitespace from CSS
- Used Kraken.io to Losslessly Compress art assets. Saved a few Megs
- Adds a file called .editorconfig, which will allow for contributors to maintain coding styles with the [.editorconfig plugin](http://editorconfig.org/) for their favourite Text Editors.
  Introduced, then fixed, a bug caused by a reckless uncorrected parameter change.
- Removed the Archive4.zip - which includes all the same contents as the repo.
- laid foundations for a Gruntfile to manage a build process and run local servers in the future (SoundJS expects to be able to XMLHttpRequest to get things, this won't work if you just open index.html on your system like a normal file in your browser)

### CODE REVIEW

**Comment by KraigWalker** [comment]
Gah... I didn't see that you had made changes already...

**Comment by sylvia43** [comment]
You're only slightly behind, you can manually merge. Also, typically commits are squashed when making pull requests but it's probably fine.

**Comment by KraigWalker** [comment]
Rebased the changes over mine. But I've also removed the Archive.zips that have been added. These sort of files shouldn't be going into source control. They add a ton of unnecessary bloat. if you want downloadable zips, Github allows you to do that.

**Comment by KraigWalker** [comment]
Imagine having a zip of a zip... Zipception... :confounded:

**Comment by sylvia43** [comment]
lol yeah that's a good idea. And if you need to access an old version of the repo... Well this is Git, isn't it?

**Comment by KraigWalker** [comment]
:wink:

**Comment by sylvia43** [comment]
nickkkkykkkkkkkykkykkk

**Comment by sylvia43** [comment]
Also zip inside a zip... Let's write a compression/encryption algorithm that takes a folder, zips it with the highest possible compression (at the cost of time to unzip), and then keep zipping it over and over with maximum compression until it takes hours to unzip.

**Comment by ncase** [comment]
As you may have noticed, I am an utter noob who uses Github as Dropbox.

**Comment by KraigWalker** [comment]
Lol np :) You should have seen me 3 years ago.

**Comment by KraigWalker** [comment]
I don't think I've ever done a rebase yet without the help site open

**Comment by sylvia43** [comment]
I just have an alias: "git up" -> "git pull --rebase"

**Comment by ncase** [comment]
**oh god I already messed things up**

I just had to force push after merging @anubiann00b 's commits where they added gitignore and removed the DS_STOREs. I hope this doesn't break anything.

**Comment by sylvia43** [comment]
It looks like it can be automerged...

Wait what commits did I make?

**Comment by sylvia43** [comment]
It wasn't me, it was @ancarda

**Comment by KraigWalker** [comment]
okay... erm... can I help out by first ascertaining what you tried to do @ncase ?

**Comment by KraigWalker** [comment]
Okay. I've looked at the current network graph and figured out what's going on.

@ncase - it's best you perform the automerge on github, then pull the changes to your local version. You're currently duplicating work that's already been done (I've already run the other commits over my work, and deleted the archive and DS_Store)

**Comment by ancarda** [comment]
@ncase: Would it be possible to either merge or close this PR? As [comment #48638320](https://github.com/ncase/coming-out-simulator-2014/pull/6#issuecomment-48638320) mentioned my handle, this PR has become a permanent part of [my mention tab](https://github.com/pulls/mentioned).

If you're unable - or unwilling - to merge or close this PR, could I ask you edit the linked comment and remove my handle?

Essentially, I use the created, assigned, mentioned, and review tabs like inboxes (to keep at zero), so it's really quite distracting to have a PR from 2014 on there as a permanent feature.

**Pull request closed without merging**
